language: python
sudo: false
install: true

services:
  - docker

env:
  - VERSION=1.0.0

before_script:
  - chmod +x ./build.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./build.sh